### PR TITLE
Regional scenario switches

### PR DESCRIPTION
**Pull request by FelicitasBeier**
Updated sim4nexus start script.
Added regional scenario switches (modules 12,15,42,56,50,60). Can be switched on via select and choosing respective country iso codes.

### CODE REVIEW

**Comment by abhimishr** [comment]
This PR breaks running the model via default config. While setting SSPs in config, the scenario config file asks for c50_scen_neff setting which is not provided in the default config. Throws the following error:

```
Apply SSP2 settings on config:
Error in setScenario(cfg, c(ssp, "NPI")) :
  Scenario setting gms$c50_scen_neff could not be found in the cfg provided.
Execution halted
```
Here ssp is SSP1 but this will fail for all SSPs

The c50_scen_neff setting exists in some user defined R scripts (`GP_final`, `inms2`, `sim4nexus`) but a setting implemented in the model should always be defined also in the deault config.

**Comment by abhimishr** [comment]
> Can be switched on via select and choosing respective country iso-codes.

Or maybe I don't understand how the new switches work. `c50_scen_neff `exists in default config but is not used in the code. It always appears with `_select `or `_noselect `or `_pasture_select `or `_pasture_noselect`. For example, the setting `c50_scen_neff_select `appears in default config but not in scenario config. Does `c50_scen_neff `from scenario config reading the `select`/`noselect `values by some mechanism or `c50_scen_neff ` is a leftover from some test settings which has to be deleted?

**Comment by abhimishr** [comment]
Similar problem with `c56_pollutant_prices_select`, `c56_pollutant_prices_noselect`, `c60_2ndgen_biodem_select`, `c60_2ndgen_biodem_noselect`. These settings all appear in the respective modules and default.vfg but not in scenario config.

**Comment by flohump** [comment]
So that means we need bugfixes in default.cfg and scenario.csv.
@FelicitasBeier : could you do that?

**Pull request merged**
