### PR TITLE
Update input to rev4.67

### PR DESCRIPTION
**Pull request by caviddhen**
## :bird: Purpose of this PR :bird:

Update input data to rev4.67, additional data to 4.08 (India changes), and calibration files

## :wrench: Checklist for PR creator :wrench:

- [ ] Labeling pull request correctly [from the label list](https://github.com/magpiemodel/magpie/labels).

* Low risk : Simple bugfixes (missing files, updated documentation, typos) or Start/output scripts
* Medium risk : New realization / Changes to existing realization / Other changes which don't modify default.cfg
* High risk : New input files (if cfg$input is changed in default.cfg) / Modification to core model (eg. changes in equations, calculations, introduction of new sets etc.) / Other changes in default.cfg

- [ ] Providing additional information based on PR label

* Low risk : No new model run needed.
* Medium risk : Default run based on the current version of the fork from which PR is made
* High risk
  * Default run from the current develop branch
  * Default run based on the current version of the fork from which PR is made

Resources_Land_Cover_Pastures_and_Rangelands (1)
Productivity_Landuse_Intensity_Indicator_Tau (2)
Resources_Land_Cover_Cropland (1)
Resources_Land_Cover_Forest (1)
Emissions_CO2_Land_Land_use_Change (1)
Emissions_CO2_Land

- [ ] :chart_with_downwards_trend: Performance loss/gain from current default behavior :chart_with_upwards_trend:
  * Current develop branch default : 4.65: 0.51 mins, 4.66: 0.59
  * This PR's default :  0.59 mins

image

- [ ] Added changes to `CHANGELOG.md`
- [ ] Compilation check (model starts without compilation errors - use `gams main.gms action=c` in model folder for testing).
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] The new code doesn't contain declared but unused parameters or variables.
- [ ] Where relevant, In-code comments added including documentation comments.
- [ ] Made sure that documentation created with [`goxygen`](https://github.com/pik-piam/goxygen) is okay (use `goxygen::goxygen()` for testing).
- [ ] Changes to [`magpie4`](https://github.com/pik-piam/magpie4) R library for post processing of model output (ideally backward compatible).
- [ ] Self-review of my own code.
- [ ] For high risk runs: validation of major model indicators - Land-use, emissions, food prices, Tau.  %Delete this line in case it is not a high risk run%

## :warning: Additional notes or warnings :warning:
NA

## :rotating_light: Checklist for RSE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] No unnecessary increase in module interfaces
- [ ] All required updates in interfaces (if any) have been properly adressed in the module contracts
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

## :rotating_light: Checklist for MAgPIE reviewer :rotating_light:

- [x] PR is labeled correctly.
- [x] `CHANGELOG` is updated correctly
- [x] No hard coded numbers and cluster/country/region names.
- [x] Changes to the model are scientifically sound
- [x] In-code comments and documentation comments are satisfactory.
- [x] model behavior/performance is satisfactory.
- [x] Requested changes (if any) were applied correctly

### CODE REVIEW

**Review by flohump — COMMENTED** [review]
Changing the input files and calibration factors is considered as high risk for model outputs. Please provide some basic validation figures (cropland, TAU, CO2 emissions), which compare the results of your branch with the current develop.

**Comment by flohump** [comment]
Thanks @caviddhen for the test runs and figures. There is a considerable spike in CO2 emission in SSA in 2020 in 4.67, which we did not have in 4.65. However, cropland, pasture, forest and TAU in SSA seem very similar. It would be good to understand where this comes from, and how this could be avoided.

**Comment by caviddhen** [comment]
> Thanks @caviddhen for the test runs and figures. There is a considerable spike in CO2 emission in SSA in 2020 in 4.67, which we did not have in 4.65. However, cropland, pasture, forest and TAU in SSA seem very similar. It would be good to understand where this comes from, and how this could be avoided.

Hm Yes it's quite a lot. Seems to stem from loss of primary forest. Would warrant some deeper digging to try and avoid, right?

image

**Comment by caviddhen** [comment]
With a manual calibration setting yield calibration for SSA back to that of rev4.65. The emissions spike is reduced but not eliminated. 


Emissions_CO2_Land_Land_use_Change (2)
Emissions_CO2_Land_Land_use_Change (3)
Resources_Land_Cover_Forest (2)
Resources_Land_Cover_Cropland (2)
Resources_Land_Cover_Cropland (3)
Resources_Land_Cover_Pastures_and_Rangelands (2)

**Review by flohump — APPROVED** [review]

**Pull request merged**
