### PR TITLE
Update additional data revision number adding ecoSysProt scenarios

### PR DESCRIPTION
**Pull request by merfort**
## :bird: Purpose of this PR :bird:

This PR updates the `additional_data` revision number to **4.32** adding the following new emission policy scenario options to `c56_emis_policy `:
- `ecoSysProtAll`
- `ecoSysProtForest` 
- `ecoSysProtPrimForest` 
- `ecoSysProtOff`
- `ecoSysProtAll_agMgmtExclN2O`
- `ecoSysProtAll_agMgmtExclCH4`

In the first 4 scenarios GHG emission policies related to ecosystem protection are gradually switched off, which in particular also involves exempting all types of GHG emissions from peatlands from the policy in `ecoSysProtForest`, `ecoSysProtPrimForest` and `ecoSysProtOff`. Other N2O and CH4 emissions, i.e those related to agricultural management, are still covered by the policy.

In `ecoSysProtAll_agMgmtExclN2O` all emission related to ecosystem protection are covered by the GHG policy (involving all types of GHGs from peatlands). Other CH4 emissions are also covered but further **N2O emissions** and other nitrogen-based pollutants are **exempted** from the GHG policy.

In `ecoSysProtAll_agMgmtExclCH4` all emission related to ecosystem protection are covered by the GHG policy (involving all types of GHGs from peatlands). Other N2O emissions and other nitrogen-based pollutants are also covered but further **CH4 emissions** are **exempted** from the GHG policy.

## :wrench: Checklist for PR creator :wrench:

- [x] Labeling pull request correctly [from the label list](https://github.com/magpiemodel/magpie/labels).

* Low risk : Simple bugfixes (missing files, updated documentation, typos) or Start/output scripts
* Medium risk : New realization / Changes to existing realization / Other changes which don't modify default.cfg
* High risk : New input files (if cfg$input is changed in default.cfg) / Modification to core model (eg. changes in equations, calculations, introduction of new sets etc.) / Other changes in default.cfg

- [x] Providing additional information based on PR label

* Low risk : No new model run needed.
* Medium risk : Default run based on the current version of the fork from which PR is made
* High risk
  * Default run from the current develop branch
  * Default run based on the current version of the fork from which PR is made

- [x] :chart_with_downwards_trend: Performance loss/gain from current default behavior :chart_with_upwards_trend:
  * Current develop branch default : 62.06568 mins
  * This PR's default :  64.74054 mins

- [x] Added changes to `CHANGELOG.md`
- [x] Compilation check (model starts without compilation errors - use `gams main.gms action=c` in model folder for testing).
- [x] No hard coded numbers and cluster/country/region names.
- [x] The new code doesn't contain declared but unused parameters or variables.
- [x] Where relevant, In-code comments added including documentation comments.
- [x] Made sure that documentation created with [`goxygen`](https://github.com/pik-piam/goxygen) is okay (use `goxygen::goxygen()` for testing).
- [x] Changes to [`magpie4`](https://github.com/pik-piam/magpie4) R library for post processing of model output (ideally backward compatible). (**Not applicable**)
- [x] Self-review of my own code.
- [x] In case of updated cellular input tgz file in default.cfg: scenario_config.csv has been updated accordingly (rcp1p9, rcp2p6 etc) (**Not applicable**)

## :warning: Additional notes or warnings :warning:
NA

## :rotating_light: Checklist for RSE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] No unnecessary increase in module interfaces
- [ ] All required updates in interfaces (if any) have been properly adressed in the module contracts
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

## :rotating_light: Checklist for MAgPIE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] Changes to the model are scientifically sound
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

### CODE REVIEW

**Comment by pfuehrlich-pik** [comment]
The code looks fine to me, but the name of the PR is a cryptic to me. Could you clarify by providing a brief explanation of the purpose of this pull request?

**Comment by merfort** [comment]
Thanks! I added a description of the new scenarios.

**Review by pfuehrlich-pik — APPROVED** [review]
Great, thanks!

**Review by flohump — APPROVED** [review]
Looks good.

**Pull request merged**
