### PR TITLE
 Added new scenario in f56_emis_policy (maccs_excl_cropland_n2o) and updated additional data revision

### PR DESCRIPTION
**Pull request by FelicitasBeier**
## Purpose of this PR

- Added new scenario in f56_emis_policy (maccs_excl_cropland_n2o) that can be chosen when combining climate policy (ghg prices) and fertilizer use efficiency. It avoids double accounting because the MACCS are switched off for all nitrogen-related emissions that are related to cropland (pasture and animal waste management are kept)

## Performance loss/gain from current default behavior

Capture

- Add an image using plot from `shinyresults::appResults()` and annotate accordingly.

- 1.102 = 0.789/0.716  (loss in performance)

## Type of change

- [ ] Bug fix (Change which fixes an issue).
- [ ] New feature (Change which adds functionality).
- [x] Minor change (Change which does not modify core model code i.e., in /modules).
- [ ] Major change (fix or feature that would change current model behavior).

## How Has This Been Tested?

- [x] Runs using starting script which tests current defaults (using `test_runs.R`).
- [x] Runs using starting script which successfully runs the same scenarios as in `test_runs.R` but with the changes from PR.
- [ ] (If applicable) Runs using different scenarios/mappings which are not the default (12 regions/c200 clusters).

## *Additions* or *Changes* to default configuration (default.cfg):
- added new scenario description in default.cfg

Changes are deletion or updates to the existing model components in default config

- [ ] Realizations:
- [ ] Scenario switches:
- [ ] Scalars/Constants:
- [ ] Model interfaces:
- [x] Others: only new scenario added in f56_emis_policy 

## Checklist:

- [x] Self-review of my own code.
- [x] Compilation check (model starts without compilation errors).
- [x] Added changes to `CHANGELOG.md`
- [x] No hard coded numbers and cluster/country/region names.
- [x] The code doesn't contain declared but unused parameters or variables.
- [x] In-code comments added including documentation comments.
- [ ] Compiled and checked resulting documentation with `goxygen::goxygen()` for the new/updated parts.
- [ ] Changes to `magpie4` R library for post processing of model output (ideally backward compatible).

## Special comments/warnings

- Notes

### CODE REVIEW

**Comment by FelicitasBeier** [comment]
I updated the scenario in the folder as discussed with Benni. It is a scenario where MACCS don't apply to N-related emissions. 
It diverges from the "all" scenario (not as before the default: redd+_nosoil) in the sense that N-related emissions for inorg_fert, man_crop, resid, resid_burn, som, rice are set to 0, while for awms and man_past still 1. 
The purpose is to avoid double accounting when activating NUE improvements while activating climate policy.

I tested it again and updated the runtime image and performance loss.

**Review by abhimishr — APPROVED** [review]
good to go

**Comment by k4rst3ns** [comment]
Seems fine.

**Review by k4rst3ns — APPROVED** [review]
seems fine.

**Review by tscheypidi — APPROVED** [review]

**Pull request merged**
