### PR TITLE
update scenario config. Added RCP scenarios for use with setScenario

### PR DESCRIPTION
**Pull request by flohump**
…R function.

## :bird: Purpose of this PR :bird:

- Added RCP scenarios to scenario_config file for use with setScenario R function. This required a change in the 1st column of the file.

## :wrench: Checklist for PR creator :wrench:

- [x] Labeling pull request correctly [from the label list](https://github.com/magpiemodel/magpie/labels).

* Low risk : Simple bugfixes (missing files, updated documentation, typos) or Start/output scripts
* Medium risk : New realization / Changes to existing realization / Other changes which don't modify default.cfg
* High risk : New input files (if cfg$input is changed in default.cfg) / Modification to core model (eg. changes in equations, calculations, introduction of new sets etc.) / Other changes in default.cfg

- [x] Providing additional information based on PR label

* Low risk : No new model run needed.
* Medium risk : Default run based on the current version of the fork from which PR is made
* High risk
  * Default run from the current develop branch
  * Default run based on the current version of the fork from which PR is made

- [ ] :chart_with_downwards_trend: Performance loss/gain from current default behavior :chart_with_upwards_trend:
  * Current develop branch default : ** mins
  * This PR's default :  ** mins

- [x] Added changes to `CHANGELOG.md`
- [x] Compilation check (model starts without compilation errors - use `gams main.gms action=c` in model folder for testing).
- [x] No hard coded numbers and cluster/country/region names.
- [x] The new code doesn't contain declared but unused parameters or variables.
- [x] Where relevant, In-code comments added including documentation comments.
- [x] Made sure that documentation created with [`goxygen`](https://github.com/pik-piam/goxygen) is okay (use `goxygen::goxygen()` for testing).
- [x] Changes to [`magpie4`](https://github.com/pik-piam/magpie4) R library for post processing of model output (ideally backward compatible).
- [x] Self-review of my own code.
- [ ] For high risk runs: validation of major model indicators - Land-use, emissions, food prices, Tau.  %Delete this line in case it is not a high risk run%

## :warning: Additional notes or warnings :warning:
NA

## :rotating_light: Checklist for RSE reviewer :rotating_light:

- [x] PR is labeled correctly.
- [x] `CHANGELOG` is updated correctly
- [x] No hard coded numbers and cluster/country/region names.
- [x] No unnecessary increase in module interfaces
- [x] All required updates in interfaces (if any) have been properly adressed in the module contracts
- [x] In-code comments and documentation comments are satisfactory.
- [x] model behavior/performance is satisfactory.
- [x] Requested changes (if any) were applied correctly

## :rotating_light: Checklist for MAgPIE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] Changes to the model are scientifically sound
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

### CODE REVIEW

**Review by k4rst3ns — COMMENTED** [review]
Just as understanding: setScenario can work with input[1] without any change to the function itself it seems (looking at: https://github.com/pik-piam/gms/blob/master/R/setScenario.R).

I thought, we anyway had to change gms:setScenario and than might very well use a different approach than trying to replace always input[1]. Hmmm @tscheypidi: You seem to be not in favour of any special rules in setScenario?

**Comment by tscheypidi** [comment]
correct....Florians solution works out of the box with the current version of `setScenario`. The reason why I am not in favor of model-specific rules in `setScenario` is that in the past these special cases often backfired in other applications and make the code hard to maintain over time. So, if possible, I would like to avoid that.

**Comment by k4rst3ns** [comment]
Ok, understood and sorry for my enthusiasm in the magpie meeting than. I guess this might be ready to go than, as I don't believe it makes sense to split up the gms$input now (as this might be to much work for the whole group to adapt o this change now). You might wanna update the lpjml_addon input order to be inline.

Only other option I see would be adding an additional cfg item that, that would work as a add-on. 
Code in default.cfg would have both items:
```
cfg$input  <- c([...all the inputs])
cfg$input_addon  <- NULL

```
and merge or overwritten within the start_function here: https://github.com/magpiemodel/magpie/blob/0d005ef36b3e0bc2cabec3f6775a6fe92c394243/scripts/start_functions.R#L204.

But I guess Jan would be not to happy with this solution, as this kind of over-writing logic comes with its pros and cons ^^'

**Review by weindl — APPROVED** [review]
The general solution works well for the coupled runs; together with the rule to always use the same ordering in the input-vector, green light from my side.

**Review by tscheypidi — APPROVED** [review]

**Comment by k4rst3ns** [comment]
I tested another idea of a named input vector like:
```
cfg$input <- c(cellular = "rev4.61_h12_42b44dcd_cellularmagpie_c200_GFDL-ESM4-ssp370_lpjml-ab83aee4.tgz",
               regional = "rev4.61_h12_magpie.tgz",
               validation = "rev4.61_h12_validation.tgz",
               calibration = "calibration_H12_newlpjml_bestcalib_fc-sticky-dynamic_crop-endoApr21-allM_20May21.tgz",
               additional = cfg$input[grep("additional_data", cfg$input)])
```
In the setScenario the only issue is, that we have to work with `input['cellular']` instead of `input["cellular"]` (which fails due to the waysetScenario reads in the scenario_config file).

I tested it and downloading worked just fine.

**Comment by flohump** [comment]
> I tested another idea of a named input vector like:
> 
> ```
> cfg$input <- c(cellular = "rev4.61_h12_42b44dcd_cellularmagpie_c200_GFDL-ESM4-ssp370_lpjml-ab83aee4.tgz",
>                regional = "rev4.61_h12_magpie.tgz",
>                validation = "rev4.61_h12_validation.tgz",
>                calibration = "calibration_H12_newlpjml_bestcalib_fc-sticky-dynamic_crop-endoApr21-allM_20May21.tgz",
>                additional = cfg$input[grep("additional_data", cfg$input)])
> ```
> 
> In the setScenario the only issue is, that we have to work with `input['cellular']` instead of `input["cellular"]` (which fails due to the waysetScenario reads in the scenario_config file).
> 
> I tested it and downloading worked just fine.

Thanks for that! I just implemented your suggested changes. Would be great if you could have a final look.

**Comment by k4rst3ns** [comment]
Just did: looks exactly how, I did it. Also tested it again: Works!
Sorry for the long discussion :) I think this is ready to pull now.

**Pull request merged**
