### PR TITLE
added consistency check that prevents yield calibration runs without using the resulting factors in the magrun

### PR DESCRIPTION
**Pull request by DavidhoPIK**
## :bird: Description of this PR :bird:

At the moment it is possible to start a yield calibration run with ```cfg$recalibrate <- "ifneeded"``` or ```"cfg$recalibrate <- TRUE"```, but then not use the resulting calibration factors in the magrun by setting ```cfg$gms$s14_use_yield_calib <- 0```.
This can lead to confusion, since the natural expectation when performing a new calibration run is that its results will also be used in the magpie run. 
Since both ```cfg$recalibrate <- "ifneeded"``` and ```"cfg$recalibrate <- TRUE"``` express the intend to use yield calibration and perform a calibration run (ifneeded), I propose to simply not allow either of theses settings together with ```cfg$gms$s14_use_yield_calib <- 0``` and stop a run with these settings with a useful error message. 

## :wrench: Checklist for PR creator :wrench:

- [x] Label pull request [from the label list](https://github.com/magpiemodel/magpie/labels).
  - **Low risk**: Simple bugfixes (missing files, updated documentation, typos) or changes  in start or output scripts
  - **Medium risk**: Uncritical changes in the model core (e.g. moderate modifications in non-default realizations)
  - **High risk**: Critical changes in model core or default settings (e.g. changing a model default or adjusting a core mechanic in the model)

- [x] Self-review own code
  - No hard coded numbers and cluster/country/region names.
  - The new code doesn't contain declared but unused parameters or variables.
  - [`magpie4`](https://github.com/pik-piam/magpie4) R library has been updated accordingly and backwards compatible where necessary.
  - `scenario_config.csv` has been updated accordingly (important if `default.cfg` has been updated)

- [x] Document changes 
  - Add changes to `CHANGELOG.md`
  - Where relevant, put In-code documentation comments
  - Properly address updates in interfaces in the module documentations
  - run [`goxygen::goxygen()`](https://github.com/pik-piam/goxygen) and verify the modified code is properly documented

- [x] Perform test runs
  - **Low risk**: 
    - Run a compilation check via `Rscript start.R --> "compilation check"`
  - **Medium risk**: 
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
  - **High risk**:
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
    - Default run from the PR target branch for comparison
    - Provide relevant comparison plots (land-use, emissions, food prices, land-use intensity,...)

### :chart_with_downwards_trend: Performance changes :chart_with_upwards_trend:
  
  - Current develop branch default : ** mins
  - This PR's default :  ** mins

## :rotating_light: Checklist for reviewer :rotating_light:

- PR is labeled correctly
- Code changes look reasonable
  - No hard coded numbers and cluster/country/region names.
  - No unnecessary increase in module interfaces
  - model behavior/performance is satisfactory.
- Changes are properly documented
  - `CHANGELOG` is updated correctly
  - Updates in interfaces have been properly addressed in the module documentations
  - In-code documentation looks appropriate
- [x] content review done (at least 1)
- [x] RSE review done (at least 1)

### CODE REVIEW

**Comment by DavidhoPIK** [comment]
I tested that indeed an error is thrown whenever ```cfg$recalibrate <- "ifneeded""``` or ```cfg$recalibrate <- TRUE``` together with ```cfg$gms$s14_use_yield_calib <- 0 ``` is selected, and that else there is no error. 
I would be interested to here from you if you belief that the error message is understandable, useful and concise enough.  
I'm happy to adjust it.

**Review by FelicitasBeier — APPROVED** [review]
Looks good to me. Thanks for including this error message. I'm sure this will prevent mistakes!

**Comment by FelicitasBeier** [comment]
> I tested that indeed an error is thrown whenever `cfg$recalibrate <- "ifneeded""` or `cfg$recalibrate <- TRUE` together with `cfg$gms$s14_use_yield_calib <- 0 ` is selected, and that else there is no error. I would be interested to here from you if you belief that the error message is understandable, useful and concise enough. I'm happy to adjust it.

I made an adjustment in the error message. You can double check whether it is clear to you and correct.

**Review by tscheypidi — APPROVED** [review]
looks good

**Comment by DavidhoPIK** [comment]
Thanks for reviewing the 

> > I tested that indeed an error is thrown whenever `cfg$recalibrate <- "ifneeded""` or `cfg$recalibrate <- TRUE` together with `cfg$gms$s14_use_yield_calib <- 0 ` is selected, and that else there is no error. I would be interested to here from you if you belief that the error message is understandable, useful and concise enough. I'm happy to adjust it.
> 
> I made an adjustment in the error message. You can double check whether it is clear to you and correct.

Thank you for revising the error message. I think it is much more concise now, yet it still conveys the important information. 
I only changed "combination of switches" to "combination of switch configurations", to emphasize that the problem is not using both switches together, but to configure them in this way. (It was probably clear before).

**Pull request merged**
