### PR TITLE
bugfix croparea correction

### PR DESCRIPTION
**Pull request by k4rst3ns**
## :bird: Purpose of this PR :bird:

- This is a hotfix for the wrong fm_croparea replacement in the crop modules and wrong proxy yields for the management calib yield realization.
- For croparea:Since sticky realization is based on this values, the current version of sticky does not allocated capital shares correctly. 
- For yields: Proxy yields for regions without historical crop specific areas had wrong proxy yield calculation, that is now fixed.
- Run time has increase quite a lot, so switching on opt file by default is necessary to get a reasonable runtime.

## :wrench: Checklist for PR creator :wrench:

- [x] Labeling pull request correctly [from the label list](https://github.com/magpiemodel/magpie/labels).
- [x] Providing additional information based on PR label
* Medium risk : Default run based on the current version of the fork from which PR is made

- [x] :chart_with_downwards_trend: Performance loss/gain from current default behavior :chart_with_upwards_trend:
  * Current develop branch default : 1.11 h
  * This PR's default :  1.32-1.44 h
  
  Some additional info
  * Without opt_file + both fixes: runtime > 3h
  -> Opt_file is needed
  * Without opt_file + only one of the fixes: 2.18 rsply 2.28 h
  -> Runtime increase is due to general in crease of complexity and does not correspond to a single change. 
  * With initializing with fm_croprea + opt_file: 2.17 h
  -> initializing doesn't help and should (for now) not be included
  * With restricting sticky (stickyfix) + opt_file: 1.79 h
  -> restricting sticky to reduce solve space size does not help

- [x] Added changes to `CHANGELOG.md`
(no changes needed??)
- [x] Compilation check (model starts without compilation errors - use `gams main.gms action=c` in model folder for testing).
- [x] No hard coded numbers and cluster/country/region names.
- [x] The new code doesn't contain declared but unused parameters or variables.
- [x] Where relevant, In-code comments added including documentation comments.
- [ ] Made sure that documentation created with [`goxygen`](https://github.com/pik-piam/goxygen) is okay (use `goxygen::goxygen()` for testing).
- [ ] Changes to [`magpie4`](https://github.com/pik-piam/magpie4) R library for post processing of model output (ideally backward compatible).
- [x] Self-review of my own code.

## :warning: Additional notes or warnings :warning:
NA

## :rotating_light: Checklist for RSE reviewer :rotating_light:

- [x] PR is labeled correctly.
- [x] `CHANGELOG` is updated correctly
- [x] No hard coded numbers and cluster/country/region names.
- [x] No unnecessary increase in module interfaces
- [x] All required updates in interfaces (if any) have been properly adressed in the module contracts
- [x] In-code comments and documentation comments are satisfactory.
- [x] model behavior/performance is satisfactory.
- [x] Requested changes (if any) were applied correctly

## :rotating_light: Checklist for MAgPIE reviewer :rotating_light:

- [ ] PR is labeled correctly.
- [ ] `CHANGELOG` is updated correctly
- [ ] No hard coded numbers and cluster/country/region names.
- [ ] Changes to the model are scientifically sound
- [ ] In-code comments and documentation comments are satisfactory.
- [ ] model behavior/performance is satisfactory.
- [ ] Requested changes (if any) were applied correctly

### CODE REVIEW

**Comment by flohump** [comment]
Thanks for spotting and fixing the bug. Please add an entry in the changelog.

**Comment by k4rst3ns** [comment]
> Thanks for the comment @flohump 

My feeling was, as both fixes are at the moment unreleased, there is no need to make a change log entry.
@tscheypidi: what do you think - is a change log entry needed?

**Comment by tscheypidi** [comment]
I agree with @k4rst3ns, a new entry in CHANGELOG might be more confusing than helpful in this particular case

**Review by flohump — APPROVED** [review]
All changes make sense to me.

**Review by tscheypidi — APPROVED** [review]

**Pull request merged**
