### PR TITLE
add cluster_resolution output script

### PR DESCRIPTION
**Pull request by pfuehrlich-pik**
## :bird: Description of this PR :bird:

- add cluster_resolution output extra script that writes shapefile with landuse data on cluster resolution to be used as basis for downscaling

## :wrench: Checklist for PR creator :wrench:

- [x] Label pull request [from the label list](https://github.com/magpiemodel/magpie/labels).
  - **Low risk**: Simple bugfixes (missing files, updated documentation, typos) or changes  in start or output scripts
  - **Medium risk**: Uncritical changes in the model core (e.g. moderate modifications in non-default realizations)
  - **High risk**: Critical changes in model core or default settings (e.g. changing a model default or adjusting a core mechanic in the model)

- [x] Self-review own code
  - No hard coded numbers and cluster/country/region names.
  - The new code doesn't contain declared but unused parameters or variables.
  - [`magpie4`](https://github.com/pik-piam/magpie4) R library has been updated accordingly and backwards compatible where necessary.
  - `scenario_config.csv` has been updated accordingly (important if `default.cfg` has been updated)

- [x] Document changes 
  - Add changes to `CHANGELOG.md`
  - Where relevant, put In-code documentation comments
  - Properly address updates in interfaces in the module documentations
  - run [`goxygen::goxygen()`](https://github.com/pik-piam/goxygen) and verify the modified code is properly documented

- [x] Perform test runs
  - **Low risk**: 
    - Run a compilation check via `Rscript start.R --> "compilation check"`
  - **Medium risk**: 
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
  - **High risk**:
    - Run test runs via `Rscript start.R --> "test runs"`
    - Check logs for errors/warnings
    - Default run from the PR target branch for comparison
    - Provide relevant comparison plots (land-use, emissions, food prices, land-use intensity,...)

### :chart_with_downwards_trend: Performance changes :chart_with_upwards_trend:
  
  - Current develop branch default : ** mins
  - This PR's default :  ** mins

## :rotating_light: Checklist for reviewer :rotating_light:

- PR is labeled correctly
- Code changes look reasonable
  - No hard coded numbers and cluster/country/region names.
  - No unnecessary increase in module interfaces
  - model behavior/performance is satisfactory.
- Changes are properly documented
  - `CHANGELOG` is updated correctly
  - Updates in interfaces have been properly addressed in the module documentations
  - In-code documentation looks appropriate
- [x] content review done (at least 1)
- [x] RSE review done (at least 1)

### CODE REVIEW

**Review by tscheypidi — APPROVED** [review]
nice script. Concerning the naming: Perhaps land_cluster_shapefile?

Concerning magpie 4 package: Often code starts just as a script and if we see that it gets more heavily used or is being used in various places it might get upgraded to a magpie4 function. But direct contributions to magpie4 are also always welcome.

In this particular case I was wondering whether it would make sense to put the "store data on cluster level into a shape file" part into a separate function which then can be applied to any kind of cluster-level data. I think that would be extremely useful.

**Review by pvjeetze — CHANGES_REQUESTED** [review]
I agree with Jan's comment. I think a more specific name that makes clear that here land output is transferred to a shape file would definitely be better. 

I also like the idea of providing a function in `magpie4` that translates any desired information to  shapefile. I think that just requires leaving line 18-21 open and pass an object to the function (e.g. land at c200) that is then merged into the attribute table of the shapefile.

The function could be named `toolClusterOutput2Shapefile` or so. @tscheypidi are tool functions allowed in `magpie4`?

**Comment by tscheypidi** [comment]
I would not call it like the tool-functions in the madrat universe to avoid confusion

**Comment by pfuehrlich-pik** [comment]
Now I'm using the newly added magpie4::clusterOutputToTerraVector that was added in https://github.com/pik-piam/magpie4/pull/44

**Review by tscheypidi — APPROVED** [review]

**Review by pvjeetze — APPROVED** [review]
Looks fine to me! Thanks Pascal!

**Pull request merged**
